[build]
  base = "culinary-app"  
  command = "npm run build"
  publish = "culinary-app/build"  
  functions = "culinary-app/netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
